platform :ios, '14.0'

# Ensure Flutter tools are available
flutter_root = File.expand_path('..', __dir__)
require File.join(flutter_root, 'flutter/bin/flutter_podhelper')

use_frameworks!
use_modular_headers!

target 'Runner' do
  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end
