platform :ios, '14.0'

# Ensure Flutter tools are available
flutter_root = `flutter --cache-dir`.strip
require File.expand_path("#{flutter_root}/bin/flutter_podhelper", __dir__)

use_frameworks!
use_modular_headers!

target 'Runner' do
  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end
