platform :ios, '14.0'

# Ensure Flutter tools are available
require_relative '../flutter_tools/bin/flutter_podhelper'

use_frameworks!
use_modular_headers!

target 'Runner' do
  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end
