name: iOS Build (No Code Signing)

on:
  push:
    branches:
      - main  # Runs on push to main branch
  pull_request:
    branches:
      - main

jobs:
  build-ios:
    runs-on: macos-latest  # Uses GitHub's macOS runner
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.19.3  # Adjust based on your Flutter version

      - name: Install Dependencies
        run: flutter pub get

      - name: Set up Xcode
        run: sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer

      - name: Install CocoaPods
        run: |
          cd ios
          pod install

      - name: Build iOS App (Without Signing)
        run: |
          flutter build ios --no-codesign

      - name: Upload iOS Build as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: ios-build
          path: build/ios/iphoneos
